[package]
name = "Abacus-Simulator"
version = "0.1.0"
edition = "2024"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[dependencies]
bevy = "0.16.0"
bevy_egui = "0.34.1"
wasm-bindgen = "0.2.100"
